### ISSUE TITLE
Currently blocked by bug in surprise

### ISSUE THREAD

**Issue by climatebrad** [learn-co-curriculum/dsc-implementing-recommender-systems#1]
See https://github.com/NicolasHug/Surprise/issues/329

until fixed, workaround is to download and unzip `http://eigentaste.berkeley.edu/dataset/archive/jester_dataset_2.zip` and save the .dat files to `~/.surprise_data/jester/`

**Comment by jessepisel** [comment]
bug is fixed in `Surprise`
